### ISSUE TITLE
Could not find module 'libfontconfig.so.1'

### ISSUE THREAD

**Issue by moi15moi** [ldo/python_fontconfig#3]
I installed python_config, but when I try to import the librairy in a file, I get this error:
```
Traceback (most recent call last):
  File "fontCollector.py", line 402, in <module>
    import fontconfig as fc
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\fontconfig.py", line 35, in <module>
    fc = ct.cdll.LoadLibrary("libfontconfig.so.1")
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libfontconfig.so.1' (or one of its dependencies). Try using the full path with constructor syntax.
```

I am on windows, so it is probably the reason why I have this issues.

**Comment by ldo** [comment]
I don’t support Windows, sorry.
